
document.getElementById("js-signup-button").addEventListener("click", function (event) {
  event.preventDefault();
console.log("HIt")
  // Create a JSON object from the form data
  const formData = {
    customerid: "", // You can leave this empty as it seems to be generated by your server.
    name: document.getElementById("name").value,
    emailid: document.getElementById("email").value,
    password: document.getElementById("password").value,
    confirmpassword: document.getElementById("confirm_password").value,
  };

 if(!Validate(formData)){
  return;
 }

  console.log("Request sent");
  fetch("/registercustomer", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(formData),
  })
    .then(response => response.json())
    .then(data => {
      console.log("Response received:", data.value);
      if (data && data.value) {
        alert(data.value.message);
      } else {
        alert("Failed: " + data.error);
      }
      window.location.href = './signin.html';
    })
    .catch(error => {
      console.error("Error:", error);
      alert("Error while creating customer profile: " + error.message);
    });
});


function Validate(formData){
  if(formData.confirmpassword != formData.password){
    showToast("Password Mismatch","danger",5000); 
    return false
  }
  return true
}


let icon = { 
  success: 
  '<span class="material-symbols-outlined">task_alt</span>', 
  danger: 
  '<span class="material-symbols-outlined">error</span>', 
  warning: 
  '<span class="material-symbols-outlined">warning</span>', 
  info: 
  '<span class="material-symbols-outlined">info</span>', 
}; 

const showToast = ( 
  message = "Sample Message", 
  toastType = "info", 
  duration = 5000) => { 
  if ( 
      !Object.keys(icon).includes(toastType)) 
      toastType = "info"; 

  let box = document.createElement("div"); 
  box.classList.add( 
      "toast", `toast-${toastType}`); 
  box.innerHTML = ` <div class="toast-content-wrapper"> 
  
                    <div class="toast-message">${message}</div> 
                    <div class="toast-progress"></div> 
                    </div>`; 
  duration = duration || 5000; 
  box.querySelector(".toast-progress").style.animationDuration = 
          `${duration / 1000}s`; 

  let toastAlready =  
      document.body.querySelector(".toast"); 
  if (toastAlready) { 
      toastAlready.remove(); 
  } 

  document.body.appendChild(box)}; 
